os: linux
dist: noble

language: python
python:
  - 3.13

install:
  # align with upstream super-linter version
  # https://github.com/super-linter/super-linter/blob/v8.7.0/dependencies/python/ruff.txt
  - pip install ruff==0.15.17
  - sudo cp -r env /etc/opt/netbox-docker

services:
  - docker

script:
  - ruff check
  - printenv DOCKER_PASSWORD_APPCO | docker login -u $DOCKER_USERNAME_APPCO --password-stdin dp.apps.rancher.io
  - IMAGE=docker.io/netboxcommunity/netbox TAG=latest docker compose up --build --dry-run
