from certifi.core import where

from core.models import ObjectType
from users.models import Group, ObjectPermission

group_admins, _ = Group.objects.get_or_create(name='admins')
group_users, _ = Group.objects.get_or_create(name='default-users')

group_admins.save()
group_users.save()

def name_to_object(name):
    print(name)
    app_label, model_name = name.split('.', 2)
    try:
        return ObjectType.objects.get(app_label=app_label, model=model_name)
    except ObjectType.DoesNotExist:
        return None

def create_permission(name: str, actions: set[str], objects: set[str]):
    # Check if it already exists
    objectpermission,_ = ObjectPermission.objects.get_or_create(
        name=name,
        actions=list(actions),
    )
    objectpermission.object_types.set([ name_to_object(x) for x in objects if  name_to_object(x) is not None])
    # Save to make sure the object has an id before adding group relationships
    objectpermission.save()
    return objectpermission

root_objects = {
'extras.webhook',
 'extras.script',
 'extras.scriptmodule',
 'core.managedfile',
 'dcim.site',
 'circuits.providernetwork',
 'circuits.circuit',
 'dcim.interface',
 'virtualization.vminterface',
 'social_django.association',
 'social_django.code',
 'social_django.nonce',
 'social_django.usersocialauth',
 'social_django.partial',
 'core.datasource',
 'core.datafile',
 'core.autosyncrecord',
 'core.job',
 'core.objecttype',
 'core.configrevision',
 'core.objectchange',
 'circuits.circuittermination',
 'circuits.circuittype',
 'circuits.provider',
 'circuits.provideraccount',
 'circuits.circuitgroup',
 'circuits.circuitgroupassignment',
 'circuits.virtualcircuittype',
 'circuits.virtualcircuit',
 'circuits.virtualcircuittermination',
 'dcim.cable',
 'dcim.cablepath',
 'dcim.consoleport',
 'dcim.consoleporttemplate',
 'dcim.consoleserverport',
 'dcim.consoleserverporttemplate',
 'dcim.device',
 'dcim.devicebay',
 'dcim.devicebaytemplate',
 'dcim.devicerole',
 'dcim.devicetype',
 'dcim.frontport',
 'dcim.frontporttemplate',
 'dcim.interfacetemplate',
 'dcim.inventoryitem',
 'dcim.location',
 'dcim.manufacturer',
 'dcim.platform',
 'dcim.powerfeed',
 'dcim.poweroutlet',
 'dcim.poweroutlettemplate',
 'dcim.powerpanel',
 'dcim.powerport',
 'dcim.powerporttemplate',
 'dcim.rack',
 'dcim.rackreservation',
 'dcim.rackrole',
 'dcim.rearport',
 'dcim.rearporttemplate',
 'dcim.region',
 'dcim.sitegroup',
 'dcim.virtualchassis',
 'dcim.moduletype',
 'dcim.modulebay',
 'dcim.module',
 'dcim.inventoryitemrole',
 'dcim.inventoryitemtemplate',
 'dcim.modulebaytemplate',
 'dcim.cabletermination',
 'dcim.virtualdevicecontext',
 'dcim.racktype',
 'dcim.macaddress',
 'ipam.aggregate',
 'ipam.ipaddress',
 'ipam.prefix',
 'ipam.rir',
 'ipam.role',
 'ipam.routetarget',
 'ipam.vrf',
 'ipam.vlangroup',
 'ipam.vlan',
 'ipam.service',
 'ipam.iprange',
 'ipam.fhrpgroup',
 'ipam.fhrpgroupassignment',
 'ipam.asn',
 'ipam.servicetemplate',
 'ipam.asnrange',
 'ipam.vlantranslationpolicy',
 'ipam.vlantranslationrule',
 'extras.configcontext',
 'extras.tag',
 'extras.taggeditem',
 'extras.journalentry',
 'extras.imageattachment',
 'extras.exporttemplate',
 'extras.customlink',
 'extras.customfield',
 'extras.savedfilter',
 'extras.cachedvalue',
 'extras.configtemplate',
 'extras.dashboard',
 'extras.bookmark',
 'extras.customfieldchoiceset',
 'extras.eventrule',
 'extras.notificationgroup',
 'extras.subscription',
 'extras.notification',
 'tenancy.tenantgroup',
 'tenancy.tenant',
 'tenancy.contactrole',
 'tenancy.contactgroup',
 'tenancy.contact',
 'tenancy.contactassignment',
 'users.user',
 'users.token',
 'users.objectpermission',
 'users.group',
 'virtualization.cluster',
 'virtualization.clustergroup',
 'virtualization.clustertype',
 'virtualization.virtualmachine',
 'virtualization.virtualdisk',
 'vpn.ikeproposal',
 'vpn.ikepolicy',
 'vpn.ipsecproposal',
 'vpn.ipsecpolicy',
 'vpn.ipsecprofile',
 'vpn.tunnelgroup',
 'vpn.tunnel',
 'vpn.tunneltermination',
 'vpn.l2vpn',
 'vpn.l2vpntermination',
 'wireless.wirelesslangroup',
 'wireless.wirelesslan',
 'wireless.wirelesslink',
 'django_rq.queue',
 'db.testmodel',
}

user_rw_objects = {
    'dcim.site',
    'circuits.providernetwork',
    'circuits.circuit',
    'dcim.interface',
    'virtualization.vminterface',
    'circuits.circuittermination',
    'circuits.circuittype',
    'circuits.provider',
    'circuits.provideraccount',
    'circuits.circuitgroup',
    'circuits.circuitgroupassignment',
    'circuits.virtualcircuittype',
    'circuits.virtualcircuit',
    'circuits.virtualcircuittermination',
    'dcim.cable',
    'dcim.cablepath',
    'dcim.consoleport',
    'dcim.consoleporttemplate',
    'dcim.consoleserverport',
    'dcim.consoleserverporttemplate',
    'dcim.device',
    'dcim.devicebay',
    'dcim.devicebaytemplate',
    'dcim.devicerole',
    'dcim.devicetype',
    'dcim.frontport',
    'dcim.frontporttemplate',
    'dcim.interfacetemplate',
    'dcim.inventoryitem',
    'dcim.location',
    'dcim.manufacturer',
    'dcim.platform',
    'dcim.powerfeed',
    'dcim.poweroutlet',
    'dcim.poweroutlettemplate',
    'dcim.powerpanel',
    'dcim.powerport',
    'dcim.powerporttemplate',
    'dcim.rack',
    'dcim.rackreservation',
    'dcim.rackrole',
    'dcim.rearport',
    'dcim.rearporttemplate',
    'dcim.region',
    'dcim.sitegroup',
    'dcim.virtualchassis',
    'dcim.moduletype',
    'dcim.modulebay',
    'dcim.module',
    'dcim.inventoryitemrole',
    'dcim.inventoryitemtemplate',
    'dcim.modulebaytemplate',
    'dcim.cabletermination',
    'dcim.virtualdevicecontext',
    'dcim.racktype',
    'dcim.macaddress',
    'ipam.aggregate',
    'ipam.ipaddress',
    'ipam.prefix',
    'ipam.rir',
    'ipam.role',
    'ipam.routetarget',
    'ipam.vrf',
    'ipam.vlangroup',
    'ipam.vlan',
    'ipam.service',
    'ipam.iprange',
    'ipam.asn',
    'ipam.servicetemplate',
    'ipam.asnrange',
    'ipam.vlantranslationpolicy',
    'ipam.vlantranslationrule',
    'extras.journalentry',
    'extras.imageattachment',
    'extras.exporttemplate',
    'extras.savedfilter',
    'extras.customfieldchoiceset',
    'tenancy.contactrole',
    'tenancy.contactgroup',
    'tenancy.contact',
    'tenancy.contactassignment',
    'virtualization.cluster',
    'virtualization.clustergroup',
    'virtualization.clustertype',
    'virtualization.virtualmachine',
    'virtualization.virtualdisk',
    'django_rq.queue',
    'netbox_documents.sitedocument',
    'netbox_documents.locationdocument',
    'netbox_documents.devicedocument',
    'netbox_documents.devicetypedocument',
    'netbox_documents.vmdocument',
}

objectpermission = create_permission(name='root', actions= {'view', 'add', 'change', 'delete' }, objects=root_objects)
objectpermission.groups.add(group_admins)
objectpermission.save()


objectpermission = create_permission(name='user-rw', actions= {'view', 'add', 'change', 'delete' }, objects=user_rw_objects)
objectpermission.groups.add(group_users)
objectpermission.save()

objectpermission = create_permission(name='user-ro', actions= {'view'},
                                     objects={'core.objectchange', 'extras.tag', 'extras.customfield', 'tenancy.tenantgroup', 'tenancy.tenant'})
objectpermission.groups.add(group_users)
objectpermission.save()
